/**
 * Train the Adaptive ML neural network and then fit probability calibration.
 *
 * Usage: npm run ww:train
 *
 * Steps:
 *   1. Train NN on full dataset (10 seeds, keep best by val accuracy), export
 *      weights to `src/wandwars/prediction/nnWeights.ts`.
 *   2. Run 5-fold CV across all four prediction models (including per-fold NN
 *      retraining), fit isotonic/Platt calibration per model, and export
 *      calibration tables + confidence thresholds to
 *      `src/wandwars/prediction/calibrationData.ts`. Also prints benchmark
 *      table + reliability diagnostics.
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

import { getUniqueHeroes, parseMatchData } from '../records/parser'
import { runBenchmarkAndCalibrate } from './benchmark'
import { buildSamples, trainRun, type RunResult } from './trainNNCore'

const NUM_RUNS = 10 // Training rounds with different seeds; keep best

// Load all raw match data from every patch folder under raw/. Each file's
// content is prefixed with a `// @patch <id>` directive so the parser tags
// every match correctly (the encoder does the same; we re-emit here because
// trainNN reads raw files directly, not the encoded blob).
const rawDir = join(import.meta.dirname!, '..', 'data', 'raw')
const PATCH_DIR_RE = /^\d{6}_\d+(?:\.\d+)*$/

let allRaw = ''
for (const entry of readdirSync(rawDir, { withFileTypes: true })) {
  if (!entry.isDirectory() || !PATCH_DIR_RE.test(entry.name)) continue
  for (const f of readdirSync(join(rawDir, entry.name))) {
    if (!f.toLowerCase().endsWith('.data')) continue
    allRaw += `// @patch ${entry.name} @data ${f}\n`
    allRaw += readFileSync(join(rawDir, entry.name, f), 'utf-8') + '\n'
  }
}

const matches = parseMatchData(allRaw)
const heroes = getUniqueHeroes(matches)
const heroIndex: Record<string, number> = {}
heroes.forEach((h, i) => (heroIndex[h] = i))
const numHeroes = heroes.length

console.log(`Heroes: ${numHeroes}, Matches: ${matches.length}`)
console.log(`\n[1/2] Training NN (${NUM_RUNS} rounds, keeping the best)...\n`)

const allSamples = buildSamples(matches, heroIndex)

let bestRun: RunResult | null = null
for (let run = 0; run < NUM_RUNS; run++) {
  const seed = 42 + run * 7919
  const result = trainRun(allSamples, numHeroes, { seed, verbose: false })
  const marker = !bestRun || result.valAcc > bestRun.valAcc ? ' ← best' : ''
  console.log(
    `Run ${(run + 1).toString().padStart(2)}/${NUM_RUNS}: val_acc=${(result.valAcc * 100).toFixed(1)}% train_acc=${(result.trainAcc * 100).toFixed(1)}% (${result.epochs} epochs)${marker}`,
  )
  if (!bestRun || result.valAcc > bestRun.valAcc) bestRun = result
}

const final = bestRun!
console.log(
  `\nBest: train_acc=${(final.trainAcc * 100).toFixed(1)}% val_acc=${(final.valAcc * 100).toFixed(1)}%`,
)

// Export weights
const round = (x: number) => Math.round(x * 1e6) / 1e6
const weightsObj = {
  heroIndex,
  embeddings: Array.from(final.params.embeddings).map(round),
  hiddenW: Array.from(final.params.hiddenW).map(round),
  hiddenB: Array.from(final.params.hiddenB).map(round),
  outputW: Array.from(final.params.outputW).map(round),
  outputB: round(final.params.outputB[0]!),
}

const weightsPath = join(import.meta.dirname!, '..', 'prediction', 'nnWeights.ts')
const weightsContent = `// Auto-generated by trainNN.ts — do not edit manually\nimport type { NNWeights } from './nn'\n\nexport const NN_WEIGHTS: NNWeights = ${JSON.stringify(weightsObj)}\n`
writeFileSync(weightsPath, weightsContent)
console.log(`Weights written to ${weightsPath}`)

// Step 2: benchmark + calibration
console.log(`\n[2/2] Running 5-fold benchmark + calibration (per-fold NN retrain)...\n`)
runBenchmarkAndCalibrate(matches, heroes)
