import type { PvpSeasonSummary } from '@/lib/types/pvp'

/* Season 7, transcribed from the report's team table and counter ladder. */
export const S7: PvpSeasonSummary = {
  season: 7,
  teams: [
    {
      id: 'rolan-twins',
      name: 'Rolan/Twins',
      heroes: ['rolan', 'elijah-lailah'],
      games: 87,
      rating: 3.79,
      tier: 1,
    },
    {
      id: 'gwyn',
      name: 'Gwyn/Gunnar/Kulu',
      heroes: ['gunnar', 'gwyneth', 'kulu'],
      games: 478,
      rating: 2.84,
      tier: 1,
    },
    {
      id: 'alna-athalia-eryndor',
      name: 'Alna/Athalia/Eryndor',
      heroes: ['alna', 'athalia', 'eryndor'],
      games: 42,
      rating: 2.35,
      tier: 1,
    },
    { id: 'evie', name: 'Evie/Orion', heroes: ['orion', 'evie'], games: 333, rating: 2.34, tier: 1 },
    {
      id: 'alna',
      name: 'Alna/Syph/Mehira',
      heroes: ['sylphira', 'alna', 'mehira'],
      games: 316,
      rating: 2.26,
      tier: 1,
    },
    {
      id: 'saida',
      name: 'Saida/Contess/Twins',
      heroes: ['contess', 'saida', 'elijah-lailah'],
      games: 323,
      rating: 1.54,
      tier: 1,
    },
    {
      id: 'evie-hepler',
      name: 'Evie/Orion/Hepler',
      heroes: ['orion', 'evie', 'hepler'],
      games: 17,
      rating: 1.11,
      tier: 2,
    },
    {
      id: 'zorya',
      name: 'Zorya/Athalia/Pandora',
      heroes: ['zorya', 'pandora', 'athalia'],
      games: 144,
      rating: 1.03,
      tier: 2,
    },
    {
      id: 'dun-pandora',
      name: 'Dun/Pandora/Cryonaia',
      heroes: ['dunlingr', 'pandora', 'cryonaia'],
      games: 20,
      rating: 0.97,
      tier: 2,
    },
    {
      id: 'thador',
      name: 'Thador/Solise',
      heroes: ['thador', 'solise'],
      games: 248,
      rating: 0.79,
      tier: 2,
    },
  ],
  counters: [
    { winner: 'rolan-twins', loser: 'evie', wins: 15, losses: 4, band: 2, anchor: 'counter-rolan-twins-vs-evie' },
    { winner: 'rolan-twins', loser: 'alna', wins: 5, losses: 1, band: 0, anchor: 'counter-rolan-twins-vs-alna' },
    { winner: 'rolan-twins', loser: 'thador', wins: 7, losses: 0, band: 0, anchor: 'counter-rolan-twins-vs-thador' },
    { winner: 'gwyn', loser: 'rolan-twins', wins: 11, losses: 4, band: 2, anchor: 'counter-gwyn-vs-rolan-twins' },
    { winner: 'gwyn', loser: 'evie', wins: 41, losses: 19, band: 2, anchor: 'counter-gwyn-vs-evie' },
    { winner: 'gwyn', loser: 'saida', wins: 51, losses: 12, band: 3, anchor: 'counter-gwyn-vs-saida' },
    { winner: 'gwyn', loser: 'evie-hepler', wins: 5, losses: 0, band: 3, anchor: 'counter-gwyn-vs-evie-hepler' },
    { winner: 'gwyn', loser: 'dun-pandora', wins: 5, losses: 0, band: 0, anchor: 'counter-gwyn-vs-dun-pandora' },
    { winner: 'gwyn', loser: 'thador', wins: 34, losses: 3, band: 3, anchor: 'counter-gwyn-vs-thador' },
    { winner: 'alna-athalia-eryndor', loser: 'gwyn', wins: 5, losses: 2, band: 2, anchor: 'counter-alna-athalia-eryndor-vs-gwyn' },
    { winner: 'alna-athalia-eryndor', loser: 'alna', wins: 5, losses: 2, band: 0, anchor: 'counter-alna-athalia-eryndor-vs-alna' },
    { winner: 'evie', loser: 'alna', wins: 28, losses: 17, band: 1, anchor: 'counter-evie-vs-alna' },
    { winner: 'evie', loser: 'zorya', wins: 26, losses: 0, band: 3, anchor: 'counter-evie-vs-zorya' },
    { winner: 'evie', loser: 'thador', wins: 17, losses: 7, band: 0, anchor: 'counter-evie-vs-thador' },
    { winner: 'alna', loser: 'gwyn', wins: 46, losses: 25, band: 1, anchor: 'counter-alna-vs-gwyn' },
    { winner: 'saida', loser: 'alna-athalia-eryndor', wins: 3, losses: 2, band: 0, anchor: 'counter-saida-vs-alna-athalia-eryndor' },
    { winner: 'saida', loser: 'evie', wins: 28, losses: 18, band: 1, anchor: 'counter-saida-vs-evie' },
    { winner: 'saida', loser: 'zorya', wins: 15, losses: 0, band: 0, anchor: 'counter-saida-vs-zorya' },
    { winner: 'zorya', loser: 'gwyn', wins: 22, losses: 18, band: 1, anchor: 'counter-zorya-vs-gwyn' },
  ],
}
