// Auto-generated by scripts/import-skills.ts; do not edit.
// Importing this module loads every skill locale file in this directory as
// one chunk; see loadSkillLocale() in src/utils/dataLoader.ts.
import type { SkillLocaleFile } from '../../../lib/types/skill'

const modules = import.meta.glob<SkillLocaleFile>('./*.json', {
  eager: true,
  import: 'default',
})

const dict: Record<string, SkillLocaleFile> = {}
for (const [path, file] of Object.entries(modules)) {
  dict[path.slice(2, -'.json'.length)] = file
}

export default dict
