// List of skills with documentation pages
// Update this when adding new skill documentation
export const DOCUMENTED_SKILLS = [
  'aliceth',
  'bonnie',
  'bryon',
  'damian',
  'dunlingr',
  'eironn',
  'elijah-lailah',
  'faramor',
  'fay',
  'hammie',
  'hewynn',
  'hugin',
  'isabella',
  'koko',
  'lily-may',
  'lyca',
  'nara',
  'mehira',
  'niru',
  'pandora',
  'parisa',
  'ravion',
  'reinier',
  'rowan',
  'scarlita',
  'shakir',
  'silvina',
  'smokey-meerky',
  'thador',
  'vala',
  'zandrok',
]
