/**
 * Dev-time utilities for building hero-portrait signatures from a folder of
 * image files chosen by the user (via `<input webkitdirectory>`). Used by the
 * pool-import UI for two flows:
 *
 *   1. "Generate Signatures" — compute + download a TypeScript module that
 *      can be committed as `heroPortraitSignatures.ts`.
 *   2. "Override Reference" — compute and hold in-memory to replace the
 *      bundled signatures at runtime without a file save.
 *
 * Both flows share `buildSignaturesFromFiles`; they diverge only in what
 * they do with the resulting map.
 */

import { computeSignature, loadImage } from './imageSignature'
import { float32ToBase64 } from './signatureCodec'

export function heroNameFromFilename(filename: string): string {
  const base = filename.split(/[/\\]/).pop() ?? filename
  return base
    .replace(/\.[^.]+$/, '')
    .toLowerCase()
    .trim()
}

export interface BuildResult {
  signatures: Record<string, Float32Array>
  skipped: Array<{ filename: string; reason: string }>
}

/**
 * Read every image file in the list, compute its signature using the same
 * pipeline as runtime screenshot cells, and key by the filename (sans ext).
 */
export async function buildSignaturesFromFiles(files: FileList | File[]): Promise<BuildResult> {
  const signatures: Record<string, Float32Array> = {}
  const skipped: BuildResult['skipped'] = []

  const list = Array.from(files).filter((f) => f.type.startsWith('image/'))
  await Promise.all(
    list.map(async (file) => {
      const name = heroNameFromFilename(file.name)
      if (!name) {
        skipped.push({ filename: file.name, reason: 'empty hero name' })
        return
      }
      const url = URL.createObjectURL(file)
      try {
        const img = await loadImage(url)
        signatures[name] = computeSignature(img)
      } catch (err) {
        skipped.push({ filename: file.name, reason: String(err) })
      } finally {
        URL.revokeObjectURL(url)
      }
    }),
  )

  return { signatures, skipped }
}

/**
 * Serialize a signature map to a committable TypeScript module.
 */
export function serializeSignaturesModule(signatures: Record<string, Float32Array>): string {
  const entries = Object.entries(signatures)
    .map(([hero, sig]): [string, string] => [hero, float32ToBase64(sig)])
    .sort((a, b) => a[0].localeCompare(b[0]))

  const header = `/**
 * Auto-generated by the in-app dev tool (see WandWarsPoolImport →
 * "Generate Signatures"). DO NOT edit by hand.
 *
 * Each value is a base64-encoded Float32Array of 1024 floats — the normalized
 * 32×32 circular-masked grayscale signature of a hero portrait. Because we
 * store the signatures directly, the source PNGs do not need to be committed
 * to the repo.
 */
export const HERO_PORTRAIT_SIGNATURES: Record<string, string> = {
`
  const body = entries
    .map(([name, b64]) => `  ${JSON.stringify(name)}: ${JSON.stringify(b64)},`)
    .join('\n')
  return header + body + '\n}\n'
}

export function downloadSignaturesFile(content: string, filename = 'heroPortraitSignatures.ts') {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
